version: "2"
services:
  qgisserver:
    restart: always
    image: gisquick/qgis-server:3.4
    volumes:
      - ./_data/publish:/publish/
    ports:
      - "90"

  django:
    restart: always
    image: gisquick/django:vue
    links:
      - qgisserver
    volumes:
      - ./_data/data/:/var/www/gisquick/data/
      - ./_data/media/:/var/www/qisquick/media/
      - ./_data/publish:/publish/
    ports:
      - "8000"
    environment:
      - GUNICORN_WORKERS=2
      - GUNICORN_ERRORLOG=-
      - GUNICORN_ACCESSLOG=-
      - DJANGO_LANGUAGE_CODE='en-us'
      - LANG=C.UTF-8
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  go:
    restart: always
    image: gisquick/settings
    volumes:
      - ./_data/publish:/publish/
    ports:
      - "8001"
    environment:
      - PROJECTS_DIR=/publish
      - SERVER_URL=http://django:8000
      - MAPSERVER_URL=http://qgisserver:90/cgi-bin/qgis_mapserv.fcgi
      - MAX_FILE_UPLOAD=50M
      - MAX_PROJECT_SIZE=200M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  nginx:
    restart: unless-stopped
    image: nginx
    links:
      - django
    volumes_from:
      - django:ro
    volumes:
      - ./nginx-conf/:/etc/nginx/gisquick/
      - ./_data/etc/letsencrypt/:/etc/letsencrypt/
      # - ./_data/var/www/certbot/:/var/www/certbot/
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=localhost
    command: ["/bin/sh","-c", "envsubst '$$NGINX_HOST' < /etc/nginx/gisquick/conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
